name: 'Send CI result to Slack'
description: 'This action intends to send the result of a CI build to a Slack channel'

runs:
  using: composite
  steps:
  - name: Slack notification
    uses: 8398a7/action-slack@v3
    with:
      status: ${{ job.status }}
      job_name: Main CI status completion
      fields: repo,message,commit,author,action,eventName,ref,workflow,job,took
      username: GitHub Actions
      icon_emoji: ':github-actions:'
      channel: 'C07FGC1FG0N'
    env:
      GITHUB_TOKEN: ${{ env.GITHUB_TOKEN }}
      SLACK_WEBHOOK_URL: ${{ env.SLACK_WEBHOOK_URL }}