name: 'List compatible Plugins'
description: 'List compatible Plugins for a particular Kestra version by requesting Kestra API.'
inputs:
  kestraVersion:
    description: "Kestra version to find compatible plugins for"
    required: true
outputs:
  plugins:
    description: "List of all Kestra OSS && EE plugins"
    value: ${{ steps.plugins.outputs.plugins }}
runs:
  using: composite
  steps:
    - name: Plugins - Get compatible plugins for Kestra version
      id: plugins
      shell: bash
      run: |
        KESTRA_VERSION=${{ inputs.kestraVersion }}
        echo "list compatible plugins for Kestra version: $KESTRA_VERSION"
        COMPATIBLE_PLUGINS=$(npx --yes @kestra-io/kestra-devtools getCompatiblePlugins $KESTRA_VERSION) 
        echo "compatible plugins $COMPATIBLE_PLUGINS"
        echo "plugins=$COMPATIBLE_PLUGINS" >> $GITHUB_OUTPUT