name: Build Artifacts

on:
  workflow_dispatch:

  workflow_call:
    secrets:
      GOOGLE_SERVICE_ACCOUNT:
        description: "The Google Service Account."
        required: true
      CODECOV_TOKEN:
        description: 'Codecov Token'
        required: true

jobs:
  build-artifacts:
    name: Build Jar
    runs-on: kestra-private-large
    env:
      GOOGLE_SERVICE_ACCOUNT: ${{ secrets.GOOGLE_SERVICE_ACCOUNT }}
      COREPACK_INTEGRITY_KEYS: 0
    steps:
      # Google Auth
      - name: GCP - Auth with unit test account
        id: auth
        if: ${{ env.GOOGLE_SERVICE_ACCOUNT != 0 }}
        uses: 'google-github-actions/auth@v3'
        with:
          credentials_json: '${{ env.GOOGLE_SERVICE_ACCOUNT }}'

      # Checkout
      - name: Checkout - EE
        uses: actions/checkout@v5
        with:
          path: kestra-ee

      - name: Checkout - OSS
        uses: kestra-io/.github/actions/kestra-ee-checkout

      - name: setup init
        uses: ./composite/setup-build
        with:
          java-enabled: 'true'
          node-enabled: 'true'

      # Shadow Jar
      - name: Gradle - Build jars
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
          NODE_OPTIONS: "--max-old-space-size=4096"
        run: |
          cd kestra-ee
          ./gradlew executableJar --parallel

      - name: Artifacts - Upload Executable
        uses: actions/upload-artifact@v4
        with:
          name: exe
          path: kestra-ee/build/executable/

      - name: Artifacts - Transform swagger for website
        run: |
          mkdir -p swagger
          cp kestra/webserver/build/classes/java/main/META-INF/swagger/kestra.yml swagger/kestra.yml
          cp kestra-ee/webserver-ee/build/classes/java/main/META-INF/swagger/kestra-ee.yml swagger/kestra-ee.yml

      - name: Artifacts - Upload Swagger
        uses: actions/upload-artifact@v4
        with:
          name: swagger
          path: swagger