name: Publish - Maven

on:
  workflow_call:
    secrets:
      GCP_SERVICE_ACCOUNT:
        required: true
    inputs:
      java-version:
        description: "Java version"
        type: string
        default: '21'
        required: false

env:
  OTLP_ENDPOINT: ${{ secrets.OTLP_ENDPOINT }}
  NODE_OPTIONS: "--max-old-space-size=4096"

jobs:
  maven:
    name: Publish - Maven
    runs-on: kestra-private-large
    # skip RCs
    if: ${{ !contains(github.ref, '-rc') }}
    env:
      COREPACK_INTEGRITY_KEYS: 0
    steps:
      # Checkout
      - name: Checkout - EE
        uses: actions/checkout@v5
        with:
          path: kestra-ee

      - name: Checkout - OSS
        uses: kestra-io/actions/composite/kestra-ee/kestra-ee-checkout@main

      - name: setup init
        uses: kestra-io/actions/composite/setup-build@main
        with:
          java-enabled: 'true'
          java-version: ${{ inputs.java-version }}

      - name: Setup - OpenTelemetry
        uses: kestra-io/actions/actions/otel-collect@main
        if: ${{ env.OTLP_ENDPOINT != '' }}
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          otlp-endpoint: ${{ secrets.OTLP_ENDPOINT }}
          otlp-headers: "${{ secrets.OTLP_HEADERS }}"
          host-metrics-enabled: 'true'
          gradle-tracing-enabled: 'true'
          service-name: "Github Actions - ${{ github.repository }} - ${{ github.workflow }}"

      # Google Auth
      - name: GCP - Auth with github service account
        id: auth
        uses: 'google-github-actions/auth@v3'
        with:
          credentials_json: '${{ secrets.GCP_SERVICE_ACCOUNT }}'

      # Publish
      - name: Publish - Release package with Gradle
        working-directory: kestra-ee
        env:
          NODE_OPTIONS: "--max-old-space-size=4096"
        run: ./gradlew publish

      # Gradle dependency
      - name: Java - Gradle dependency graph
        if: ${{ github.ref == 'refs/heads/develop' }}
        uses: gradle/actions/dependency-submission@v4
        with:
          build-root-directory: kestra-ee

  otel-export-trace:
    if: always()
    name: OpenTelemetry Export Trace
    runs-on: kestra-private-standard
    needs: [ maven ]
    steps:
      - name: OpenTelemetry - Export trace
        uses: kestra-io/actions/actions/otel-collect@main
        if: ${{ env.OTLP_ENDPOINT != '' }}
        with:
          mode: export-all
          github-token: ${{ secrets.GITHUB_TOKEN }}
          otlp-endpoint: ${{ secrets.OTLP_ENDPOINT }}
          otlp-headers: "${{ secrets.OTLP_HEADERS }}"
          logs-enabled: 'true'
          service-name: "Github Actions - ${{ github.repository }} - ${{ github.workflow }}"
