name: Build Artifacts

on:
  workflow_call: {}

jobs:
  build:
    name: Build - Artifacts
    runs-on: ubuntu-latest
    outputs:
      docker-tag: ${{ steps.vars.outputs.tag }}
      docker-artifact-name: ${{ steps.vars.outputs.artifact }}
      plugins: ${{ steps.plugins.outputs.plugins }}
    env:
      PLUGIN_VERSION: ${{ github.event.inputs.plugin-version != null && github.event.inputs.plugin-version || 'LATEST' }}
    steps:
      - name: Checkout - Current ref
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      # Npm
      - name: Setup - Npm install
        shell: bash
        working-directory: ui
        run: npm ci

      # Setup build
      - uses: kestra-io/actions/composite/setup-build@main
        name: Setup - Build
        id: build
        with:
          java-enabled: true
          node-enabled: true

      # Get Plugins List
      - name: Plugins - Get List
        uses: kestra-io/actions/composite/kestra-oss/kestra-oss-plugins-list@main
        if: "!startsWith(github.ref, 'refs/tags/v')"
        id: plugins-list
        with:
          plugin-version: ${{ env.PLUGIN_VERSION }}

      # Set Plugins List
      - name: Plugins - Set List
        id: plugins
        if: "!startsWith(github.ref, 'refs/tags/v')"
        shell: bash
        run: |
          PLUGINS="${{ steps.plugins-list.outputs.plugins }}"
          TAG=${GITHUB_REF#refs/*/}
          if [[ $TAG = "master" || $TAG == v* ]]; then
            echo "plugins=$PLUGINS" >> $GITHUB_OUTPUT
          else
            echo "plugins=--repositories=https://central.sonatype.com/repository/maven-snapshots/ $PLUGINS" >> $GITHUB_OUTPUT
          fi

      # Build
      - name: Gradle - Build
        shell: bash
        run: |
          ./gradlew executableJar

      - name: Artifacts - Copy exe to image
        shell: bash
        run: |
          cp build/executable/* docker/app/kestra && chmod +x docker/app/kestra

      # Upload artifacts
      - name: Artifacts - Upload JAR
        uses: actions/upload-artifact@v4
        with:
          name: jar
          path: build/libs/

      - name: Artifacts - Upload Executable
        uses: actions/upload-artifact@v4
        with:
          name: exe
          path: build/executable/
