name: Frontend - Tests

on:
  workflow_call:
    secrets:
      GITHUB_AUTH_TOKEN:
        description: "The GitHub Token."
        required: true
      CODECOV_TOKEN:
        description: 'Codecov Token'
        required: true

env:
  # to save corepack from itself
  COREPACK_INTEGRITY_KEYS: 0

jobs:
  test:
    name: Frontend - Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Cache Node Modules
        id: cache-node-modules
        uses: actions/cache@v4
        with:
          path: |
            ui/node_modules
          key: modules-${{ hashFiles('ui/package-lock.json') }}

      - name: Cache Playwright Binaries
        id: cache-playwright
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/ms-playwright
          key: playwright-${{ hashFiles('ui/package-lock.json') }}

      - name: Npm - install
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        working-directory: ui
        run: npm ci

      - name: Npm - lint
        uses: reviewdog/action-eslint@v1
        with:
          github_token: ${{ secrets.GITHUB_AUTH_TOKEN }}
          reporter: github-pr-review
          workdir: ui

      - name: Npm - Run build
        working-directory: ui
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        run: npm run build

      - name: Run front-end unit tests
        working-directory: ui
        run: npm run test:unit -- --coverage

      - name: Storybook - Install Playwright
        working-directory: ui
        if: steps.cache-playwright.outputs.cache-hit != 'true'
        run: npx playwright install --with-deps

      - name: Run storybook component tests
        working-directory: ui
        run: npm run test:storybook -- --coverage
