name: 'Upload Jar'
description: 'This action uploads the jar as artifact and comments the download link on the pull request'

inputs:
  secrets:
    description: 'Secrets passed as toJSON'
    required: true

runs:
  using: composite
  steps:
    - name: Artifacts - Upload JAR
      uses: actions/upload-artifact@v4
      with:
        name: jar
        path: "**/build/libs/*.jar"
        retention-days: 7

    - name: Artifacts - Comment pull request
      uses: kestra-io/actions/actions/comment-update@main
      with:
        github-token: ${{ fromJson(inputs.secrets).GITHUB_TOKEN }}
        title: "📦 Artifacts"
        fetch-artifact: 'true'
        add-summary: 'false'
        template: |
          {% if artifacts | length > 0 %}
          | Name | Size | Updated | Expiration |
          | :--- | :--- | :--- | :--- |
          {%- for artifact in artifacts %}
          | [![{{ artifact.name }}](https://img.shields.io/badge/Download%20{{ artifact.name }}-8405FF?style=flat-square)]({{ artifact.download_url }}) | {{ artifact.size_in_bytes | prettySize }} | {{ artifact.updated_at | prettyDate }} | {{ artifact.expires_at | prettyDate }} |
          {%- endfor %}
          {% endif %}
